theme: minima
exclude: ['README.md', 'Gemfile.lock', 'Gemfile']

title: 'SHARP impact assessment'
baseurl: /sharp-ia


activities-title: Activities and outputs
activities:
- title:  Partnerships
  link:   "#partnerships"
  icon:   assets/images/icon-partnerships.png
- title:  Safe environment
  link:   "#safe-environment"
  icon:   assets/images/icon-safe-environment.png
- title:  Local setting
  link:   "#local-setting"
  icon:   assets/images/icon-local-setting.png
- title:  Assessments
  link:   "#assessments"
  icon:   assets/images/icon-assessments.png
- title:  Interventions
  link:   "#interventions"
  icon:   assets/images/icon-interventions.png
- title:  Research and innovation
  link:   "#research-innovation"
  icon:   assets/images/icon-research-innovation.png
- title:  Right support
  link:   "#right-support"
  icon:   assets/images/icon-right-support.png

outcomes-title: Outcomes and impact
outcomes:
- title:  Reduced cost to services
  link:   "#reduced-cost"
  icon:   assets/images/icon-reduced-cost.png
- title:  Increased social inclusion and well-being 
  link:   "#social-inclusion"
  icon:   assets/images/icon-social-inclusion.png  
